In [4]:
import numpy as np
a = np.array([1, 2, 3]) 
print(a.shape)

(3,)


In [7]:
a=np.array([[2,3,4],[4,2,1]])
a.shape
#a[:,None]
#a.shape

(2, 3)

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [8]:
a.shape
a[None,:].shape
a[:,None].shape
a[None,:]
a[:,None]

(3,)

(1, 3)

(3, 1)

array([[1, 2, 3]])

array([[1],
       [2],
       [3]])

In [22]:
b=np.zeros((2,3))
b
b.shape

array([[0., 0., 0.],
       [0., 0., 0.]])

(2, 3)

In [18]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a[0]
for idx in enumerate(a):
    print(idx)
for x in enumerate(a):
    print(x)
for idx,x in enumerate(a):
    print(idx)

array([1, 2, 3, 4])

(0, array([1, 2, 3, 4]))
(1, array([5, 6, 7, 8]))
(2, array([ 9, 10, 11, 12]))
(0, array([1, 2, 3, 4]))
(1, array([5, 6, 7, 8]))
(2, array([ 9, 10, 11, 12]))
0
1
2


In [21]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b[:,1]
b[:,1].shape

array([ 2,  6, 10])

(3,)

In [26]:
# the array has a shape(4,3,2)
c=np.ones((4,3,2))
c
c[:,0,:]
c[:,0,:].shape

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

(4, 2)

In [32]:
d=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[10,11]]])
d
d.shape
d[:,0,:]

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [10, 11]]])

(2, 3, 2)

array([[1, 2],
       [7, 8]])

In [37]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

# Q1. Get subset of "a" consisting of
#    the 1st & 3rd rows and
#    the 1st & 2nd columns
a[[0,2],0:2]

# Q2. get the last two rows and last two columns
a[-2:,-2:]

# Q3. Reverse the order of columns, 
#    i.e. the first column becomes the last
b=[1,2,3,4]
b[::-1]
a[:,::-1]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[ 1,  2],
       [ 9, 10]])

array([[ 7,  8],
       [11, 12]])

[4, 3, 2, 1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [38]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]

In [41]:
a
b
b[0, 0] = 77
a
# A slice of an array is **a view into the same data**, 
# so modifying it will modify the original array.

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[77,  3],
       [ 6,  7]])

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
b1=np.copy(b)
b1[0,0]=100
b
b1

array([[77,  3],
       [ 6,  7]])

array([[100,   3],
       [  6,   7]])

In [45]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[a>2])
# np.where returns the locations 
# satisfying the condition
# as a tuple of lists
# each list gives locations at one dimension
#npy
print(np.where(a>2))

[3 4 5 6]
(array([1, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))


In [46]:
a = np.array([[4,2], [3, 4], [5, 0]])
print("before change:", a)

# if a value >3, set it to 3
a[np.where(a>3)]=3
print("after change:", a)

before change: [[4 2]
 [3 4]
 [5 0]]
after change: [[3 2]
 [3 3]
 [3 0]]


In [84]:
# binarize the array, 
# if a value>3, set it to 1; otherwise, 0
a = np.array([[4,2], [3, 4], [5, 0]])
np.where(a>3,1,0)
#np.where(a>3,1)
# if a value belong to [0,3], set it to 1, >=3, set it to 2, <=0 ,set it to 0?
#np.where(a<=0,0<a<3,a>=3,0,1,2)
np.where(a>=3,2,np.where(a<=0,0,1))

array([[1, 0],
       [0, 1],
       [1, 0]])

array([[2, 1],
       [2, 2],
       [2, 0]])

In [64]:
x = np.array([[1,2],[3,4],[3,5]])
x.sum()
x.sum(axis=0) #sum of each column
x.sum(axis=1) #sume of each row

18

array([ 7, 11])

array([3, 7, 8])

In [87]:
a=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[10,11]]])

In [82]:
a
b=np.array([[3]])
b.shape
b=np.array([3])
b.shape

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [10, 11]]])

(1, 1)

(1,)

In [90]:
a
a.shape
sum_2=a.sum(axis=-1)
sum_2
sum_2.shape
sum_2=a.sum(axis=-1,keepdims=True)
sum_2
sum_2.shape

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [10, 11]]])

(2, 3, 2)

array([[ 3,  7, 11],
       [15, 19, 21]])

(2, 3)

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [21]]])

(2, 3, 1)

In [92]:
x = np.array([[1,2],[3,4],[5,6]])
x
x.T

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1, 3, 5],
       [2, 4, 6]])

In [98]:
# Exercise 1.4.5: Term-Frequency Matrix:
# each row is a document
# each column is a word
# value at [i,j] is the count of word j in document i

tf=np.array([[0,5,0,1,2], [1,0,4,0,2], [0,2,3,1,2]])

# 1. Count total occurrences of each word
np.sum(tf,axis=0)
# 2. Find the length of each document
np.sum(tf,axis=1)
# 3. Fill the term-frequency matrix 
#    with binary values (1: present, 0: not present)
np.where(tf>0,1,0)
# 4. count document frequency of each word 
#    i.e. the number of documents that contain the word
np.sum(np.where(tf>0,1,0),axis=0)
# 5. Find the most frequent word in each document
np.argsort(tf)[]

array([1, 7, 7, 2, 6])

array([8, 7, 8])

array([[0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 1, 1, 1]])

array([1, 2, 2, 2, 3])

array([[0, 2, 3, 4, 1],
       [1, 3, 0, 4, 2],
       [0, 3, 1, 4, 2]], dtype=int64)

In [14]:
# Exercise 1.5.4: Compute squared sample error (SSE)
# d is the sample matrix where each row is a sample
# SSE=(d-mean(d))^2
d=np.random.randint(0,10,(100,5))
#sse=(d-np.mean(d))
#np.sum(np.square(sse))
print(np.mean(d,axis=0))
print(np.mean(d))
#what is the difference
print(np.sum(d))
print(np.sum(d,axis=0))

[4.72 3.8  4.56 4.13 4.79]
4.4
2200
[472 380 456 413 479]


In [4]:
import numpy as np
import pandas as pd
x=np.array([[1,2,10],[3,4,8],[2,2,3],[3,1,4],[1,2,2]])
#x[:,0]
pd.crosstab(index=x[:,0],columns=x[:,1],rownames='A',colnames='B')

B  1  2  4
A         
1  0  2  0
2  0  1  0
3  1  0  1