In [1]:
import numpy as np
import csv
import pandas as pd

In [2]:
 arr=np.array([[0,1,0,2,0,1],[1,0,1,1,2,0],[0,0,2,0,0,1]])

In [39]:
def analyze_tf(arr, binary=False):
    
    tf_idf=None
    
    # add your code
    if binary==True:
        tf_idf=np.where(arr>=1,1,0)
    #print(tf)
    
    
    return tf_idf

In [40]:
print(analyze_tf(arr,binary=True))

[[0 1 0 1 0 1]
 [1 0 1 1 1 0]
 [0 0 1 0 0 1]]


In [42]:
n=arr.shape[0]
print(n)

3


In [37]:
temp=np.sum(arr,axis=1)
print(temp)
temp.shape
print("\n")
print(arr)
arr.shape
print("\n")
result=arr/temp[:,None]
print(result)

[4 5 3]


[[0 1 0 2 0 1]
 [1 0 1 1 2 0]
 [0 0 2 0 0 1]]


[[0.         0.25       0.         0.5        0.         0.25      ]
 [0.2        0.         0.2        0.2        0.4        0.        ]
 [0.         0.         0.66666667 0.         0.         0.33333333]]


In [48]:
df=np.sum(np.where(arr>=1,1,0),axis=0)
print(df)
print(n/df)

[1 1 2 2 1 2]
[3.  3.  1.5 1.5 3.  1.5]


In [70]:
def analyze_tf(arr, binary=False):
    
    tf_idf=None
    
    # add your code
    if binary==True:
        arr_b=np.where(arr>=1,1,0)
        temp=np.sum(arr_b,axis=1)
        tf=arr_b/temp[:,None]
        df=np.sum(np.where(arr_b>=1,1,0),axis=0)
        N=arr_b.shape[0]
        idf=N/df
        tf_idf=tf*np.log(idf)
    else:
        temp=np.sum(arr,axis=1)
        tf=arr/temp[:,None]
        df=np.sum(np.where(arr>=1,1,0),axis=0)
        N=arr.shape[0]
        idf=N/df
        tf_idf=tf*np.log(idf)
    
    return tf_idf

In [71]:
arr=np.array([[0,1,0,2,0,1],[1,0,1,1,2,0],[0,0,2,0,0,1]])
print(arr, binary = False)

TypeError: 'binary' is an invalid keyword argument for this function

In [72]:
def analyze_tf(arr, binary=False):
    
    tf_idf=None
    
    # add your code
    if binary==True:
        arr_b=np.where(arr>=1,1,0)
        temp=np.sum(arr_b,axis=1)
        tf=arr_b/temp[:,None]
        df=np.sum(np.where(arr_b>=1,1,0),axis=1)
        N=arr_b.shape[0]
        idf=N/df
        tf_idf=np.array([tf*math.log(i) for i in idf])
    else:
        temp=np.sum(arr,axis=1)
        tf=arr/temp[:,None]
        df=np.sum(np.where(arr>=1,1,0),axis=1)
        N=arr.shape[0]
        idf=N/df
        tf_idf=np.array([tf*math.log(i) for i in idf])
    
    return tf_idf

In [69]:
arr=np.array([[0,1,0,2,0,1],[1,0,1,1,2,0],[0,0,2,0,0,1]])


array([1, 1, 2, 2, 1, 2])

In [3]:
data=pd.read_csv('cars.csv',header=0)
data

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
5    15.0          8           429        198    4341          10.0     70   
6    14.0          8           454        220    4354           9.0     70   
7    14.0          8           440        215    4312           8.5     70   
8    14.0          8           455        225    4425          10.0     70   
9    15.0          8           390        190    3850           8.5     70   
10   15.0          8           383        170    3563          10.0     70   
11   14.0          8           340        160    3609           8.0     70   
12   15.0          8           400        150    3761           9.5     70   
13   14.0          8           455        225    3086          10.0     70   
14   24.0          4           113         95    2372          15.0     70   
15   22.0          6           198         95    2833          15.5     70   
16   18.0          6           199         97    2774          15.5     70   
17   21.0          6           200         85    2587          16.0     70   
18   27.0          4            97         88    2130          14.5     70   
19   26.0          4            97         46    1835          20.5     70   
20   25.0          4           110         87    2672          17.5     70   
21   24.0          4           107         90    2430          14.5     70   
22   25.0          4           104         95    2375          17.5     70   
23   26.0          4           121        113    2234          12.5     70   
24   21.0          6           199         90    2648          15.0     70   
25   10.0          8           360        215    4615          14.0     70   
26   10.0          8           307        200    4376          15.0     70   
27   11.0          8           318        210    4382          13.5     70   
28   27.0          4            97         88    2130          14.5     71   
29   28.0          4           140         90    2264          15.5     71   
..    ...        ...           ...        ...     ...           ...    ...   
166  29.0          4            97         75    2171          16.0     75   
167  23.0          4           140         83    2639          17.0     75   
168  20.0          6           232        100    2914          16.0     75   
169  23.0          4           140         78    2592          18.5     75   
170  24.0          4           134         96    2702          13.5     75   
171  25.0          4            90         71    2223          16.5     75   
172  24.0          4           119         97    2545          17.0     75   
173  18.0          6           171         97    2984          14.5     75   
174  29.0          4            90         70    1937          14.0     75   
175  19.0          6           232         90    3211          17.0     75   
176  23.0          4           115         95    2694          15.0     75   
177  23.0          4           120         88    2957          17.0     75   
178  22.0          4           121         98    2945          14.5     75   
179  25.0          4           121        115    2671          13.5     75   
180  33.0          4            91         53    1795          17.5     75   
181  28.0          4           107         86    2464          15.5     76   
182  25.0          4           116         81    2220          16.9     76   
183  25.0          4           140         92    2572          14.9     76   
184  26.0          4            98         79    2255          17.7     76   
185  27.0          4        

In [5]:
data["Brand"]=data.apply(lambda x:x.car.split()[0],axis=1)
data

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
5    15.0          8           429        198    4341          10.0     70   
6    14.0          8           454        220    4354           9.0     70   
7    14.0          8           440        215    4312           8.5     70   
8    14.0          8           455        225    4425          10.0     70   
9    15.0          8           390        190    3850           8.5     70   
10   15.0          8           383        170    3563          10.0     70   
11   14.0          8           340        160    3609           8.0     70   
12   15.0          8           400        150    3761           9.5     70   
13   14.0          8           455        225    3086          10.0     70   
14   24.0          4           113         95    2372          15.0     70   
15   22.0          6           198         95    2833          15.5     70   
16   18.0          6           199         97    2774          15.5     70   
17   21.0          6           200         85    2587          16.0     70   
18   27.0          4            97         88    2130          14.5     70   
19   26.0          4            97         46    1835          20.5     70   
20   25.0          4           110         87    2672          17.5     70   
21   24.0          4           107         90    2430          14.5     70   
22   25.0          4           104         95    2375          17.5     70   
23   26.0          4           121        113    2234          12.5     70   
24   21.0          6           199         90    2648          15.0     70   
25   10.0          8           360        215    4615          14.0     70   
26   10.0          8           307        200    4376          15.0     70   
27   11.0          8           318        210    4382          13.5     70   
28   27.0          4            97         88    2130          14.5     71   
29   28.0          4           140         90    2264          15.5     71   
..    ...        ...           ...        ...     ...           ...    ...   
166  29.0          4            97         75    2171          16.0     75   
167  23.0          4           140         83    2639          17.0     75   
168  20.0          6           232        100    2914          16.0     75   
169  23.0          4           140         78    2592          18.5     75   
170  24.0          4           134         96    2702          13.5     75   
171  25.0          4            90         71    2223          16.5     75   
172  24.0          4           119         97    2545          17.0     75   
173  18.0          6           171         97    2984          14.5     75   
174  29.0          4            90         70    1937          14.0     75   
175  19.0          6           232         90    3211          17.0     75   
176  23.0          4           115         95    2694          15.0     75   
177  23.0          4           120         88    2957          17.0     75   
178  22.0          4           121         98    2945          14.5     75   
179  25.0          4           121        115    2671          13.5     75   
180  33.0          4            91         53    1795          17.5     75   
181  28.0          4           107         86    2464          15.5     76   
182  25.0          4           116         81    2220          16.9     76   
183  25.0          4           140         92    2572          14.9     76   
184  26.0          4            98         79    2255          17.7     76   
185  27.0          4        

In [103]:
origin=data[data.origin==1]
origin.sort_values(by='mpg',ascending=False).iloc[0:3,[0,8]]

mpg                  car
194  29.0   chevrolet chevette
82   28.0      dodge colt (sw)
29   28.0  chevrolet vega 2300

In [96]:
origin=data[data.origin==1].sort_values(by='mpg',ascending=False).iloc[0:3,:].loc[:,['mpg','car']]
origin

NameError: name 'oringin' is not defined

In [82]:
def car_analysis(filepath):
    data=pd.read_csv(filepath,header=0)
    print(data)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
5    15.0          8           429        198    4341          10.0     70   
6    14.0          8           454        220    4354           9.0     70   
7    14.0          8           440        215    4312           8.5     70   
8    14.0          8           455        225    4425          10.0     70   
9    15.0          8           390        190    3850           8.5     70   
10   15.0          8           383        170    3563          10.0     70   
11   14.0          8           340        160    3609           