# <center>Assignment 2</center>

## Q1. Define a function to analyze a numpy array
 - Assume we have an array which contains term frequency of each document. Where each row is a document, each column is a word, and the value denotes the frequency of the word in the document. Define a function named "analyze_tf" which:
      * has two input parameters: 
        * a rank 2 input array
        * a parameter "binary" with a default value set to False
      * does the following steps in sequence:
        1. if "binary" is True, binarizes the input array, i.e. if a value is greater than 1, change it to 1. 
        2. normalizes the frequency of each word as: word frequency divided by the length of the document (i.e. sum of each row). Save the result as an array named **tf** (i.e. term frequency). The sum of each row of tf should be 1.
        3. calculates the document frequency (**df**) of each word, i.e. how many documents contain a specific word
        4. calculate the inverse document frequency (**idf**) of each word as ** N/df ** (df divided by N) where N is the number of documents
        5. calculates **tf_idf** array as: **tf * log (idf)** (tf multiply the log (base e) of idf ). The reason is, if a word appears in most documents, it does not have the discriminative power and often is called a "stop" word. The inverse of df can downgrade the weight of such words.
      * returns the tf_idf array.
 - Note, for all the steps, ** do not use any loop**. Just use array functions and broadcasting for high performance computation.

## Q2. Define a function to analyze car dataset using pandas
 - Define a function named "analyze_cars" to do the follows:
   * Take a csv file path string as an input. Assume the csv file is in the format of the provided sample file.
   * Read the csv file as a dataframe with the first row as column names
   * Find cars with top 3 mpg among those of origin = 1. Print the names (i.e. "car" column) and mpg of these three cars.
   * Create a new column called "brand" to store the brand name as the first word in "car" column (hint: use "apply" function)
   * Show the mean, min, and max mpg values for each of these brands: "ford", "buick" and "honda"
   * Create a cross tab to show the average mpg of each brand and each origin value. Use "brand" as row index and "origin" as column index. 
 - This function does not have any return. Just print out the result of each calculation step.

## Q3 (Bonus). More sophisticated analyze_tf function
 - Assume we have an array which contains term frequency of each document. Where each row is a document, each column is a word, and the value denotes the frequency of the word in the document. Define a function named "advanced_analyze_tf" which:
      * has three input parameters: 
        * a rank 2 input array
        * a parameter "min_df" (minimum document frequency) with a default value set to 0 
        * a parameter "max_words" (maximum number of words) with a default value set None
      * process the input array as follows in sequence:
        1. if "min_df">0, remove words with document frequency (df) less than "min_df", i.e. the corresponding columns are removed 
        2. if "max_words"> 0 and "max_words" < the total number of columns (M), only words with top "max_words" frequency (df) are kept. M - "max_words" columns are removed from the array
      * call the analyze_tf function in Q1 using the resulting array to get an tf_idf array
      * returns tf_idf and the original indexes of remaining words.
 - Note, for all the steps, ** do not use any loop**. Just use array functions and broadcasting for high performance computation.

## Submission Guideline##
- Following the solution template provided below. Use __main__ block to test your functions
- Save your code into a python file (e.g. assign2.py) that can be run in a python 3 environment. In Jupyter Notebook, you can export notebook as .py file in menu "File->Download as".
- Make sure you have all import statements. To test your code, open a command window in your current python working folder, type "python assign1.py" to see if it can run successfully.

In [ ]:
# Structure of your solution to Assignment 1 

import numpy as np
import csv
import pandas as pd


def car_analysis(filepath):
    # add your code
    
def analyze_tf(arr, binary=False):
    
    tf_idf=None
    
    # add your code
    
    return tf_idf

def advanced_analyze_tf(arr, min_df=0, max_words=None):
    
    tf_idf=None
    
    # add your code
    
    return tf_idf

# best practice to test your class
# if your script is exported as a module,
# the following part is ignored
# this is equivalent to main() in Java

if __name__ == "__main__":  
    
    # Test Question 1
    arr=np.array([[0,1,0,2,0,1],[1,0,1,1,2,0],[0,0,2,0,0,1]])
    
    print(arr, binary=False)
    # You should get 
    # [[0.         0.27465307 0.         0.20273255 0.         0.10136628]
     # [0.21972246 0.         0.08109302 0.08109302 0.43944492 0.        ]
      #[0.         0.         0.27031007 0.         0.         0.13515504]]
   
    print(arr, binary=True)
    # You should get
     #[[0.         0.3662041  0.         0.13515504 0.         0.13515504]
     # [0.27465307 0.         0.10136628 0.10136628 0.27465307 0.        ]
     # [0.         0.         0.20273255 0.         0.         0.20273255]]
    
    # test question 2
    
    car_analysis('../../dataset/cars.csv')
    
    # test question 3
    
    tf_idf, selected_words=advanced_analyze_tf(arr, min_df=2, max_words=3)