# <center>Arrays for Scientific Computation</center>
References:
* Numpy Quickstart Tutorial: https://docs.scipy.org/doc/numpy-1.14.0/user/quickstart.html
* Numpy Tutorial: http://cs231n.github.io/python-numpy-tutorial/#numpy
* Broadcasting arrays in Numpy, https://eli.thegreenplace.net/2015/broadcasting-arrays-in-numpy/

## 1. Numpy
- Numpy is the core library for scientific computing in Python. It provides high-performance multidimensional array objects, and tools for working with these arrays. 

- A numpy **array** is a grid of values, usually of the same type, although technically you can store values of different types (this may complicate array operation). 
    - The number of dimensions is the **rank** of the array
    - The **shape** of an array is a tuple of integers giving the size of the array along each dimension
      * e.g. array([5, 2, 3]) has shape (3,) 
      * e.g. array([[5, 2, 3], [1,2,3]]) has shape (2,3)
    - Numpy arrays can be initialized from nested Python lists, and access elements using square brackets

In [1]:
# enable interactiveShell
# so that Jupyter will display variables or 
# unassigned output of a statement 
# without the need for a print statement

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# import numpy package
import numpy as np


In [ ]:
# Exercise 1.1. Initialize an array from list

# Create a rank 1 array
a = np.array([1, 2, 3])  

print ("data type:", type(a))

# Note, (3,) means a tuple with only one element, 
# to have a tuple with only one element, 
# the "," at the end  is mandatory
print("array shape, ",a.shape)

# following the same indexing rule to access elements
print("the first element:", a[0])

# Change an element of the array
a[0] = 5                 
a

In [ ]:
# Exercise 1.2. Create a rank 2 array from list of lists

b = np.array([[1,2,3],[4,5,6]])   
b

print ("b's shape:", b.shape) 

# an array with rank 2 can be sliced in each dimension 
print("value at (0,0): ", b[0, 0])
print("value at (1,2): ", b[1, 2])   

x=np.array([1,2,3])
x.shape
x[None,:].shape  # (1,3)
x[:,None].shape # (3,1)

# array of shape (1,3)

np.array([[1,2,3]]).shape

# array of shpae (3,1)
np.array([[1],[2],[3]]).shape


In [ ]:
# Exercise 1.3. Create a rank 2 array of all zeros

a = np.zeros((2,2))  
a

In [ ]:
# Exercise 1.4. Create a rank 2 array of all ones

b = np.ones((3,2))   
b

In [ ]:
# Exercise 1.5. Create a constant array

c = np.full((2,2), 7) 
c

In [ ]:
# Exercise 1.6. a 2x2 identity matrix

d = np.eye(2)        
d

In [ ]:
# Exercise 1.7. # Create a matrix filled with random values

# uniform distributed random floats within [0, 1.0)
np.random.rand(2,2)  # shape (2,2)
np.random.random((2,2)) # shape (2,2)

# randint(low, high, size): random integer
np.random.randint(1, 6, (4,5))

# randn(d0, d1, ...dn): random floats 
# from normal distribution with shape (d0,d1,..., dn)

np.random.randn(4,3,2)

### 1.1. Array Slicing
 - **Similar to Python lists, numpy arrays can be sliced**. 
 - Since arrays may be multidimensional, you must **specify a slice for each dimension of the array**
 - **A slice of an array is a view into the same data**, so modifying it will modify the original array.

In [ ]:
# Exercise 1.1.1 Get a specific row

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# get the first row
a[0]      
# a[0,:] does the same too

# shape of the first row
a[0].shape

# what if the array has shape (4,3,2)? 
# what is the shape of its first row?

# loop through all rows
for idx,row in enumerate(a):
    print(idx, row)


In [ ]:
a=np.random.randn(4,3,2)
a
a[:,0,:].shape
print(a[:,0,:])

In [ ]:
# Exercise 1.1.2 Get a specific column

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# get the first column
column_1=a[:, 0]      
column_1

# shape of 1st column
column_1.shape

# Question: if array X has shape (4,3,2)
# what is the shape of X[:,0,:]?

In [ ]:
# Exercise 1.1.3 Get subarrays

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

# Use slicing to pull out the subarray 
# consisting of the first 3 rows
# and 2nd and 3rd columns 

b = a[0:3, 1:3]
b


In [ ]:
# Exercise 1.1.4 

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

# Q1. Get subset of "a" consisting of
#    the 1st & 3rd rows and
#    the 1st & 2nd columns
a[[0,2], 0:2]

# Q2. get the last two rows and last two columns
a[-2:, -2:]

# Q3. Reverse the order of columns, 
#    i.e. the first column becomes the last
a[:, ::-1]

# Note, for Q1, can you use a[[0,2], [0,1]]?

In [ ]:
# Exercise 1.1.5: Modify slice

# A slice of an array is **a view into the same data**, 
# so modifying it will modify the original array.

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# b is a slice
b = a[:2, 1:3]

print ("Original value at (0,1):", a[0, 1])  
b[0, 0] = 77    

# b[0, 0] is the same piece of data as a[0, 1]
print ("Modified value at (0,1):", a[0, 1])  

# how to avoid modifying the original array? 
b1=np.copy(b)
b1[0,0]=100
a

### 1.2. Boolean array indexing (Selection by conditions)

- Boolean array indexing lets you pick out arbitrary elements of an array. 
- Frequently this type of indexing is used to select elements of an array that satisfy some conditions. 
- Typically it's used with function **np.where**

In [ ]:
# Exercise 1.2.1: boolean array indexing

a = np.array([[1,2], [3, 4], [5, 6]])

# Find the elements of "a" that are bigger than 2;
# this returns a numpy array of Booleans of the same
# shape as a, where value tells
# whether that element of a is > 2

bool_idx = (a > 2)  

bool_idx

In [ ]:
# Exercise 1.2.2: Select values >2

print (a[bool_idx])

# We can do all of the above in a single 
# concise statement:
print (a[a > 2])

# note the result is 1-dimension array

In [ ]:
# Exercise 1.2.3: Find locations where value>2

a = np.array([[1,2], [3, 4], [5, 6]])
a
# np.where returns the locations 
# satisfying the condition
# as a tuple of lists
# each list gives locations at one dimension

print(np.where(a>2))
a[np.where(a>2)]

In [ ]:
# Exercise 1.2.4: change values by conditions

a = np.array([[4,2], [3, 4], [5, 0]])
print("before change:", a)

# if a value >3, set it to 3
a[np.where(a>3)]=3
print("after change:", a)

# binarize the array, 
# if a value>3, set it to 1; otherwise, 0
a = np.array([[4,2], [3, 4], [5, 0]])
print("Binarized array:", np.where(a>3, 1, 0))

### 1.3. Array Math

- Basic mathematical functions operate **elementwise** on arrays, and are available both as operator overloads and as functions in the numpy module
- Pay attention to the difference between **elementwise product** and **dot product**

In [ ]:
# Exercise 1.3.1: array addition

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Elementwise sum; both produce the array
print (x + y)
print (np.add(x, y))

In [ ]:
# Exercise 1.3.2: Subtraction

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#Elementwise difference; both produce the array
print (x - y)
print (np.subtract(x, y))

In [ ]:
# Exercise 1.3.3:  Elementwise product

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print (x * y)
print (np.multiply(x, y))

In [ ]:
# Exercise 1.3.4:  dot product

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

np.dot(x, y)
x.dot(y)

# compare the result with Exercise 1.3.3

In [ ]:
# Exercise 1.3.4:  Elementwise division

print (x / y)
print (np.divide(x, y))


In [ ]:
# Exercise 1.3.5:  Elementwise square/square root/log/...
x = np.array([[1,2],[3,4]])
np.sqrt(x)

### 1.4. Other useful array functions

- Numpy provides many useful functions for performing computations on arrays
    - **sum/mean/min/max/std**  along different dimensions
    - **transpose**
    - ** reshape **
    - ** sort ** and **argsort**

In [ ]:
# Exercise 1.4.1:  array sum/mean/max/min/std

x = np.array([[1,2],[3,4],[3,5]])
x
# Compute sum of all elements; prints "10"
print ("sum of all elements:",np.sum(x))  
# or directly use x.sum()

# Compute sum of all rows (dimension 0)
# return 1-dimension array
print ("sum of each column:", np.sum(x, axis=0))  

# Compute sum of all columns (dimension 1)
# return 1-dimension array
print ("sum of each row:", np.sum(x, axis=1))  

In [ ]:
#  high-rank array sum/mean/max/min/std

a=np.random.randn(4,3,2)

# sum along the last dimension
sum_2=a.sum(axis=-1)

# the dimension selected for sum will 
# be removed in the sum
sum_2.shape
sum_2

# Question: how to keep the sum with the same rank?
#           use argument keepdims

In [ ]:
# Exercise 1.4.2:  Array transpose
x = np.array([[1,2],[3,4],[5,6]])
print("shape of x:", x.shape)
print ("transpose of x:", x.T)
print("shape of the transpose of x:", x.T.shape)

In [ ]:
# Exercise 1.4.2:  Array reshape

x = np.array([[1,2],[3,4],[5,6]])

# reshape it to 2x3 matrix
print("reshape to 2x3 matrix:", np.reshape(x, (2,3)))
# note that this is different from transpose

# flatten the matrix into 1-dimension array
print ("flatten x:", np.reshape(x, -1))

In [ ]:
# Exercise 1.4.3:  Array sort 

x = np.array([[8,2],[3,4],[5,2]])
x
# sort each row of the matrix
print(np.sort(x))

# sort each column of the matrix
print(np.sort(x, axis=0)[::-1,:])

# how to sort in descending order?


In [ ]:
# Exercise 1.4.4:  Array argsort

x = np.array([[3,2,5,6,1],[3,4,1,2,6]])
x
# sort each row and return the **original index of each value**
# in an array of the same shape as x
x1=np.argsort(x)
x1

# How can this function be useful?

# how to find the indexes of the smallest/largest 
# 3 values in each row ? 

# how to find the indexes of the top 1 value
# in each column?


In [ ]:
# Exercise 1.4.5: Term-Frequency Matrix:
# each row is a document
# each column is a word
# value at [i,j] is the count of word j 
# in document i

tf=np.array([[0,5,0,1,2], [1,0,4,0,2], [0,2,3,1,2]])

# 1. Count total occurrences of each word
np.sum(tf, axis=0)

# 2. Find the length of each document
np.sum(tf, axis=1)

# 3. Fill the term-frequency matrix 
#    with binary values (1: present, 0: not present)
np.where(tf>0,1,0)

# 4. count document frequency of each word 
#    i.e. the number of documents that contain the word
np.sum(np.where(tf>0,1,0), axis=0)

# 5. Find the most frequent word in each document
np.argsort(tf, axis=1)[:,-1]

### 1.5. Broadcasting
- Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations
- Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.
- Example - Normalization:
    - subtract each samples by mean vector
    - divide each sample row by feature std vector (1-dimension array)  
- It would be very inefficient to use a loop to achieve this given a large matrix


In [2]:
# Exercise 1.5.1:  Successful broadcasting

# Add the vector B to each row of A

import time

A = np.random.random((10000,4))
B = np.array([10,6,8,5])
print("1st row before addition ", A[0])

# By loop:
start=time.time()   # get starting time
for row in A:
    row+=B
print("time used: %.4f ms"%(time.time()-start))

print("1st row after addition ", A[0])

1st row before addition  [0.45200652 0.6438101  0.23954135 0.37043327]
time used: 0.0191 ms
1st row after addition  [10.45200652  6.6438101   8.23954135  5.37043327]


In [3]:
# By Broadcasting
A = np.random.random((10000,4))
B = np.array([10,6,8,5])
print("1st row before addition ", A[0])

start=time.time()
A = A + B
print("time used: %.4f ms"%(time.time()-start))

print("1st row after addition ", A[0])

1st row before addition  [0.42310425 0.8268061  0.31427845 0.80603246]
time used: 0.0004 ms
1st row after addition  [10.42310425  6.8268061   8.31427845  5.80603246]


In [4]:
# Exercise 1.5.2:  Failed broadcasting

# Add a vector to each column of A
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
B = np.array([1, 0, 1, 4])
Z = A + B
print (Z)



ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

### 1.6. Broadcasting Rules:
1. Assume two arrays A and B. 
   - <font color='blue'>For example, A has size(10000, 4), B has size (4,). A has rank 2, and B has rank 1</font>
2. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
    - <font color='blue'>Padding 1 to the left of the shape of B. So B's shape becomes (1,4)</font>
3. The two arrays are said to be **compatible** in a dimension **if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension**. If compatible, continue to Step 4; otherwise stop and raise an error
    
    - Compare the shapes of A and B in each dimension: 
        * <font color='blue'>Dimension 1: A is 10000 and B is 1 => compatible </font>   
        * <font color='blue'> Dimension 2: A is 4 and B is 4 => compatible</font> 
    - <font color='blue'> So, A and B are compatible in every dimension</font>
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
    - <font color='blue'> After brodcasting, B's shape => (10000,4)</font>
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension
    - <font color='blue'> Suppose B=([1, 0, 1]). After broadcasting, B => [ [1, 0, 1],[1, 0, 1],... ]</font>
6. Apply array math using B after broadcasting

In [5]:
# Exercise 1.5.3:  revisit Exercise 1.5.3

# Add a vector to each column of A
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
B = np.array([1, 0, 1, 4])

# A's shape (4,3), B's shape (1,4)
# It's incompatible with A at the 2nd dimension

# However, after transpose A
# they are compatible
Z = A.T + B  
print (Z.T)

Z=A+B[:,None]
Z

[[ 2  3  4]
 [ 4  5  6]
 [ 8  9 10]
 [14 15 16]]


array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [14, 15, 16]])

In [6]:
# Exercise 1.5.4: Compute squared sample error (SSE)
# d is the sample matrix where each row is a sample
# SSE=(d-mean(d))^2

d=np.random.randint(0,10,(100,5))  # populate random numbers between 0 and 10 in an array of size (100, 5)
np.sum(np.square(d-np.mean(d, axis=0)))

4184.5199999999995

## 2. Sparse Matrix
- Why sparse matrix
    * In some matrixes (e.g. document-term matrix), most of the elements are zero. These matrices are called **sparse matrices**, while the ones that have mostly non-zero elements are called **dense matrices**.
    * These matrixes usually are very big. It needs memory to store every number
- Sparse matrix: a matrix that **only stores non-zero elements**. 
- Scipy package provides different types of sparse matrix. Commonly used types:
    * csc_matrix: Compressed Sparse Column format
    * csr_matrix: Compressed Sparse Row format
- Sparse matrixes can be manipulated almost in the same way as a dense matrix. Check https://docs.scipy.org/doc/scipy/reference/sparse.html for functions for sparse matrixes.

In [7]:
# Exercise 2.1: Define a sparse matrix

import numpy as np
from scipy.sparse import csr_matrix
A = csr_matrix([[1, 0, 0], [0, 0, 3], [4, 0, 5]])
print(A)
print(A[2,1])
A.shape

  (0, 0)	1
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5
0


(3, 3)

In [8]:
# Exercise 2.2: Sparse matrix math

A = csr_matrix([[1, 0, 0], [0, 0, 3], [4, 0, 5]])
v = np.array([1, 0, -1])
A.dot(v)

array([ 1, -3, -1], dtype=int64)