In [1]:
import numpy as np
a = np.array([[1, 2, 3],[2,3,4],[3,4,5]]) 
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [2]:
np.argsort(a)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [7]:
np.argsort(a)[:,::-1][0,0:2]

array([2, 1], dtype=int64)